INSERT INTO ingredient(name, photo, saison)
VALUES ('Carotte', 'carotte.jpg', "toute_l'annee"),
('Épinard', 'epinard.jpg', "toute_l'annee"),
('Lentilles', 'lentilles.jpg', "toute_l'annee"),
('Artichaut', 'artichaut.jpg', 'printemps/ete'),
('Avocat', 'avocat.jpg', 'automne/hiver'),
('Betterave', 'betterave.jpg', 'automne/hiver'),
('Radis', 'radis.jpg', 'printemps'),
('Chou rouge', 'chou_rouge.jpg', 'automne/hiver'),
('Choux de Bruxelles', 'chou_de_bruxelles.jpg', 'automne/hiver'),	
('Chou-fleur', 'chou_fleur.jpg', 'automne/hiver'),	
('Brocoli', 'Brocoli.jpg', 'ete/automne'),
('Champignon de paris', 'champignons_de_paris.jpg', 'automne/hiver'),
('Cèpe', 'cepes.jpg', 'ete/automne'),
('Morille', 'morilles.jpg', 'printemps'),
('Truffe', 'truffe.jpg', 'automne/hiver'),
('Laitue', 'salade_laitue.jpg', 'printemps/ete'),
('Blette', 'Blettes.jpg', 'ete/automne'),
('Céleri-branche', 'celeri_branche.jpg', "toute_l'annee"),
('Fenouil', 'fenouil.jpg', 'ete/automne'),
('Fève', 'feves.jpg', 'printemps'),
('Oignon', 'oignon.jpg', 'automne/hiver'),
('Rutabaga', 'rutabaga.jpg', 'automne/hiver'),	
('Panais', 'panais.jpg', 'automne/hiver'),
('Pomme de terre', 'pomme_de_terre.jpg', 'automne/hiver'),
('Asperge', 'asperge.jpg', 'printemps'),
('Navet', 'navet.jpg', "toute_l'annee"),
('Poireau', 'poireaux.jpg', 'automne/hiver'),
('Ail', 'ail.jpg', 'ete/automne'),
('Échalote', 'echalote.jpg', 'hiver'),
('Herbes aromatiques fraîches', 'herbes_aromatiques.jpg', 'printemps/ete'),	
('Oseille', 'oseille.jpg', 'printemps/ete'),
('Persil', 'persil.jpg', "toute_l'annee"),
('Courges et potimarrons', 'courge_et_potimarron.jpg', 'automne/hiver'),
('Courgette', 'courgette.jpg', 'printemps/ete'),
('Potiron', 'potiron.jpg', 'automne/hiver'),
('Aubergine', 'aubergine.jpg', 'ete/automne'),
('Concombre', 'concombre.jpg', 'printemps/ete'),
('Poivron', 'poivron.jpg', 'ete'),
('Tomate', 'tomate.jpg', 'printemps/ete'),
('Melon', 'melon.jpg', 'ete'),
('Mâche', 'mache.jpg', 'automne/hiver'),
('Cresson', 'cresson.jpg', "toute_l'annee"),
('Endive', 'endives.jpg', 'automne/hiver'),
('Patate douce', 'Patate_douce.jpg', "toute_l'annee"),
('Haricot vert', 'haricots_verts.jpg', 'ete'),
('Petit pois', 'petits_pois.jpg', 'printemps'),
('Pois gourmand', 'pois_gourmand.jpg', "toute_l'annee"),
('Moutarde', 'moutarde.jpg', "toute_l'annee"),
('Mayonnaise', 'mayonnaise.jpg', "toute_l'annee"),
('Curry', 'curry.jpg', "toute_l'annee"),
('Huile de friture', 'huile_de_friture.jpg', "toute_l'annee"),
('Feuille de brick', 'feuille_de_brick.jpg', "toute_l'annee"),
('Sauce soja', 'sauce_soja.jpg', "toute_l'annee"),
('Vin blanc', 'vin_blanc.jpg', "toute_l'annee"),
('Pain', 'pain.jpg', "toute_l'annee"),
('Comté', 'comte.jpg', "toute_l'annee"),
('Galette de riz', 'galette_de_riz.jpg', "toute_l'annee"),
('Vermicelle', 'vermicelle.jpg', "toute_l'annee"),
('Poulet', 'poulet.jpg', "toute_l'annee"),
('Germe de soja', 'germe_de_soja.jpg', "toute_l'annee"),
('Menthe', 'menthe.jpg', "toute_l'annee"),
('Crevette', 'crevette.jpg', "toute_l'annee"),
('Sauce nem', 'sauce_nem.jpg', "toute_l'annee"),
('Fromage', 'fromage.jpg', "toute_l'annee"),
('Lait', 'lait.jpg', "toute_l'annee"),
('Basilic', 'basilic.jpg', "toute_l'annee"),
('Armagnac', 'armagnac.jpg', "toute_l'annee"),
('Veau', 'veau.jpg', "toute_l'annee"),
('Saucisse', 'saucisse.jpg', "toute_l'annee"),
('Gélatine', 'gelatine.jpg', "toute_l'annee"),
('Sucre', 'sucre.jpg', "toute_l'annee"),
('Aneth', 'aneth.jpg', "toute_l'annee"),
('Saumon Fumé', 'saumon_fume.jpg', "toute_l'annee"),
('Farine', 'farine.jpg', "toute_l'annee"),
('Porc', 'porc.jpg', "toute_l'annee"),
('Foie de veau', 'foie_de_veau.jpg', "toute_l'annee"),
('Épices', 'epices.jpg', "toute_l'annee"),
('Crème fraiche', 'creme_fraiche.jpg', "toute_l'annee"),
('Muscade', 'muscade.jpg', "toute_l'annee"),
('Pate feuilletée', 'pate_feuilletee.jpg', "toute_l'annee"),
('Boeuf haché', 'boeuf_hache.jpg', "toute_l'annee"),
('Oeuf', 'oeuf.jpg', "toute_l'annee"),
("Huile d'olive", "huile_d_olive.jpg", "toute_l'annee"),
('Saumon', 'saumon.jpg', "toute_l'annee"),
('Beurre', 'beurre.jpg', "toute_l'annee"),
('Céleri rave', 'celeri_rave.jpg', "toute_l'annee"),
('Clou de girofle', 'clou_de_girofle.jpg', "toute_l'annee"),
('Bouquet garni', 'bouquet_garni.jpg', "toute_l'annee"),
('Cube bouillon', 'cube_bouillon.jpg', "toute_l'annee"),
('Sel', 'sel.jpg', "toute_l'annee"),
('Poivre', 'poivre.jpg', "toute_l'annee"),
('Kiri', 'kiri.jpg', "toute_l'annee"),
("Côte d'agneau", "cote_d_agneau.jpg", "toute_l'annee"),
('Agneau', 'agneau.jpg', "toute_l'annee"),
('Biche', 'biche.jpg', "toute_l'annee"),
('Boeuf', 'boeuf.jpg', "toute_l'annee"),
('Caille', 'caille.jpg', "toute_l'annee"),
('Canard', 'canard.jpg', "toute_l'annee"),
('Cheval', 'cheval.jpg', "toute_l'annee"),
('Chevreuil', 'chevreuil.jpg', "toute_l'annee"),
('Dinde', 'dinde.jpg', "toute_l'annee"),
('Lapin', 'lapin.jpg', "toute_l'annee"),
('Mouton', 'mouton.jpg', "toute_l'annee"),
('Pintade', 'pintade.jpg', "toute_l'annee"),
('Sanglier', 'sanglier.jpg', "toute_l'annee"),
('Côte de porc', 'cote_de_porc.jpg', "toute_l'annee"),
('Poitrine de porc', 'poitrine_de_porc.jpg', "toute_l'annee"),
('Filet mignon', 'filet_mignon.jpg', "toute_l'annee"),
('Lardons', 'lardons.jpg', "toute_l'annee"),
("Carré d'agneau", "carre_d'agneau.jpg", "toute_l'annee"),
('Cabillaud', 'cabillaud.jpg', "toute_l'annee"),
('Merlu', 'merlu.jpg', "toute_l'annee"),
('Merlan', 'merlan.jpg', "toute_l'annee"),
('Sole', 'sole.jpg', "toute_l'annee"),
('Lieu noir', 'lieu_noir.jpg', "toute_l'annee"),
('Lieu jaune', 'lieu_jaune.jpg', "toute_l'annee"),
('Truite', 'truite.jpg', "toute_l'annee"),
('Ketchup', 'ketchup.jpg', "toute_l'annee"),
('Pâte brisée', 'pate_brisee.jpg', "toute_l'annee"),
('Pâte sablée', 'pate_sablee.jpg', "toute_l'annee"),
('Riz', 'riz.jpg', "toute_l'annee"),
('Origan', 'origan.jpg', "toute_l'annee"),
('Thym', 'thym.jpg', "toute_l'annee"),
('Laurier', 'laurier.jpg', "toute_l'annee"), 
('Pâte', 'pate.jpg', "toute_l'annee"),
('Parmesan', 'parmesan.jpg', "toute_l'annee"),
('Pastèque', 'pasteque.jpg', 'ete'),
('Mangue', 'mangue.jpg', 'printemps/ete'),
('Goyave', 'goyave.jpg', 'automne'),
('Grenade', 'grenade.jpg', 'automne/hiver'),
('Ananas', 'ananas.jpg', 'automne/hiver'),
('Figue', 'figue.jpg', 'ete'),
('Fruit de la passion', 'fruit_de_la_passion.jpg', "toute_l'annee"),
('Groseille', 'groseille.jpg', 'ete'),
('Mûre', 'mure.jpg', 'ete/automne'),
('Myrtille', 'myrtille.jpg', 'ete'),
('Cassis', 'cassis.jpg', 'ete'),
('Fraise', 'fraise.jpg', 'printemps'),
('Framboise', 'framboise.jpg', 'printemps/ete'),
('Noisette', 'noisette.jpg', 'automne'),
('Kiwi', 'kiwi.jpg', 'hiver/printemps'),
('Raisin', 'raisin.jpg', 'ete/automne'),
('Pomme', 'pomme.jpg', "toute_l'annee"),
('Poire', 'poire.jpg', "toute_l'annee"),
('Coing', 'coing.jpg', 'automne'),
('Prune', 'prune.jpg', 'ete'),
('Pêche', 'peche.jpg', 'ete'),
('Abricot', 'abricot.jpg', 'ete'),
('Cerise', 'cerise.jpg', 'printemps/ete'),
('Mirabelle', 'mirabelle.jpg', 'ete'),
('Nectarine', 'nectarine.jpg', 'ete'),
('Noix de coco', 'noix_de_coco.jpg', 'automne/hiver'),
('Noix', 'noix.jpg', 'automne'),
('Amande', 'amande.jpg', 'ete/automne'),
('Châtaigne', 'chataigne.jpg', 'automne'),
('Rhubarbe', 'rhubarbe.jpg', 'printemps/ete'),
('Citron jaune', 'citron_jaune.jpg', "toute_l'annee"),
('Citron vert', 'citron_vert.jpg', "toute_l'annee"),
('Pomelos', 'pomelos.jpg', 'hiver/printemps'),
('Orange', 'orange.jpg', 'hiver/printemps'),
('Clémentine', 'clementine.jpg', 'automne/hiver'),
('Chocolat noir', 'chocolat_noir.jpg', "toute_l'annee"), 
('Chocolat au lait', 'chocolat_au_lait.jpg', "toute_l'annee"), 
('Chocolat blanc', 'chocolat_blanc.jpg', "toute_l'annee"), 
('Sucre glace', 'sucre_glace.jpg', "toute_l'annee"), 
('Yaourt nature', 'yaourt_nature.jpg', "toute_l'annee"), 
('Sucre vanillé', 'sucre_vanille.jpg', "toute_l'annee"), 
('Levure chimique', 'levure_chimique.jpg', "toute_l'annee"),
('Confiture à la fraise', 'confiture_a_la_fraise.jpg', "toute_l'annee"), 
('Vermicelles au chocolat blanc', 'vermicelle_au_chocolat_blanc.jpg', "toute_l'annee");