INSERT INTO recettes (niveau, title, details, photo, time_preparation, cook_time) VALUES
('facile','Pain de viande rapide',"ÉTAPE 1 Mettre dans le robot le persil et l'oignon. ÉTAPE 2 quelque secondes, puis ajouter le pain coupé en petits dés, mixer quelque secondes.ÉTAPE 3 Ajouter la viande, le sel, le poivre, le ketchup, l'oeuf et la muscade. ÉTAPE 4 Mixer 5 secondes ÉTAPE 5 Mettre le hachis dans un plat en lui donnant la forme d'une boule de pain. ÉTAPE 6 Cuire 45 min à 175°C, thermostat 5-6.","https://assets.afcdn.com/recipe/20131120/10837_w420h289c1cx205cy141.webp", "10", "45" ),

('facile','Tartiflette irlandaise',"Mettre dans un plat une couche de pomme de terre (moitié de la quantité - coupées en rondelles)puis une couche d'oignons (moitié de la quantité - coupés en rondelle) puis de saumon (coupé en lanières). Renouveller l'opération 1 fois. Finir par le comté et arroser des 2 briques de crème fraîche + poivre + sel (pas trop, car le saumon fumé est déjà salé).Mettre au four thermostat 6 (180°C) pendant 1h30.","https://assets.afcdn.com/recipe/20140116/11055_w1200h1641c1cx1246cy1704.webp", "20", "60" ),

('facile','Brocoli rôti',"Graisser les empreintes des moules à muffin. Placer des tranches de poitrine dans chaque moule à muffin pour recouvrir le fond et les côtés. Préchauffer le four à 180°C (thermostat 6). Enfourner 5 minutes pour assécher la poitrine. Parsemer de morceaux d'oignon vert. Casser un oeuf dans chaque empreinte, poivrer. Enfourner 15 minutes. Déguster bien chaud.","https://assets.afcdn.com/recipe/20140116/11055_w1200h1641c1cx1246cy1704.webp", "25", "30" ),

('facile','Filet mignon en croûte rapide',"Dérouler votre pâte à tarte. Y mettre votre filet mignon. L'enduire de moutarde, saler un peu, poivrer. L'envelopper de la pâte. Battre l'oeuf et en appliquer sur le dessus. Cuire au four préchauffé à 180°C (thermostat 6) pendant 30 min.","https://assets.afcdn.com/recipe/20200622112094_w1200h1800c1cx1920cy2880cxb3840cyb5760.webp", "10", "30" ),

('facile',"Riz cantonais rapide et facile","Cuire le riz comme indiqué sur le paquet. Mettre à chauffer 1 cuillère d'huile dans une poêle et y faire revenir les oignons finement émincés, les petits pois et les lardons pendant environ 4 minutes. Il est possible à ce moment-là de rajouter un peu de jus contenu dans la boîte de petits pois pour parfumer. Réserver. Battre les oeufs après les avoir salés et poivrés. Faire ensuite une omelette dans la même poêle et la couper en lamelles. Réserver. Mettre à nouveau une cuillère d'huile à chauffer et faire revenir le tout (riz, oignons, petits pois, lardons, lamelles d'omelette), sans cesser de remuer pendant environ 3 minutes. Saler et poivrer. Voilà, le plat est bien chaud, prêt à être dégusté... alors bon appétit !","https://i2.wp.com/www.programme-malin.com/wp-content/uploads/2020/12/riz-cantonnais.jpg?fit=1920%2C1080&ssl=1", "10", "20" ),

('facile',"Penne aux courgettes","Mettez à cuire les pâtes. Lavez et coupez la courgette en dés. Faire suer la courgette dans l'huile un instant, puis ajoutez 1 pincée d'origan, de thym et la feuille de laurier. Versez les tomates coupées en dés. Laissez cuire jusqu'à ce que les courgettes soient cuites. Assaisonner un peu selon votre goût. Egouttez les pâtes et disposez les dans une jolie assiette. Versez les courgettes dessus. Saupoudrez de parmesan.","https://i2.wp.com/www.programme-malin.com/wp-content/uploads/2020/12/riz-cantonnais.jpg?fit=1920%2C1080&ssl=1", "10", "10" )




